#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-1 I II III IV
bspc monitor HDMI-0 V VI VII VIII IX X

bspc config border_width        2
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh

# change the desktop number here
FLOATING_DESKTOP_ID=$(bspc query -D -d '^3')

bspc subscribe node_manage | while read -a msg ; do
   desk_id=${msg[2]}
   wid=${msg[3]}
   [ "$FLOATING_DESKTOP_ID" = "$desk_id" ] && bspc node "$wid" -t floating
done
